name: Build
on:
  push:
#     branches:
#       - '*'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        working-directory: docs
        run: npm install
      - name: Build
        working-directory: docs
        run: npm run build
      - name: Install Laf-CLI
        run: npm i laf-cli -g
      - name: Login laf-cli
        working-directory: docs
        env:
          LAF_PAT: ${{ secrets.LAF_PAT }}
        run: |
          mkdir build
          cd build/
          laf login -r https://api.laf.dev $LAF_PAT
          laf app init y7lnyy
          ls
          cd ..
          ls
          cp .vitepress/dist build/
          cd build/
          
        
        

