name: Build
on:
  push:
    branches:
      - '*'
      - '!main'
      
env:
  BUCKET_NAME: "y7lnyy-doc"
  LAF_APPID: "y7lnyy"
  LAF_PAT: ${{ secrets.LAF_PAT }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        working-directory: docs
        run: npm install
      - name: Build
        working-directory: docs
        run: npm run build
      - name: Install Laf-CLI
        run: npm i laf-cli -g
      - name: Login laf-cli
        working-directory: docs          
        run: laf login -r https://api.laf.dev $LAF_PAT
      - name: Init appid
        working-directory: docs/.vitepress
        env:
          LAF_APPID: ${{ env.LAF_APPID }}
        run: |
          laf app init ${{ env.LAF_APPID }}
          ls
          laf storage push -f ${{ env.BUCKET_NAME }} dist/
